### ISSUE TITLE
Documentation for configuring for database-only support.

### ISSUE THREAD

**Issue by patricknelson** [hafriedlander/silverstripe-hybridsessions#5]
Currently there's no immediately obvious way to configure this module to **strictly** use the database only for session storage. I ended up figuring this out on my own by setting up the following in my `config.yml` file:

``` yml
HybridSessionStore:
  handlers:
    - HybridSessionStore_Database
```

While simple, this took frustratingly long to figure out without documentation.
